### ISSUE TITLE
Setting page-load timeout not working

### ISSUE THREAD

**Issue by ggiunta** [webdriverio/webdriverjs-angular#6]
Setting it as described on WebDriverIO API:

http://webdriver.io/api/protocol/timeouts.html

`webdriver.timeouts("page load", 30000);`

But I keep getting timeouts. It's not waiting for the amount of time I set, seems like it completely ignores it:

```
Error: [url("https://ui-dev.oneflowcloud.com/#/login")] <= 
 Timeout while waiting for page to load
  at [object Object].hasTimeout (/Users/germangiunta/Dev/OneFlow/node_modules/webdriverjs-angular/index.js:47:12)
  at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by vvo** [comment]
Default timeout is 10s for the page to load in webdriverjs-angular, we could make this customizable, see https://github.com/webdriverio/webdriverjs-angular/blob/bcf25dbe969af1b5f23d8460c80b5a87463040d4/index.js#L43-L66

**Comment by ggiunta** [comment]
It would be great to make it customisable as webdriverio allows you to set it.
